---
title: "Balancing Utility and Privacy"
bibliography: ../references.bib
---

-   contradictory ideals, but enable each other

*summarize ideas by* @Jansen2025_TensionOpenData

# Measuring Privacy

-   Calculate privacy levels (k-anonymity) and compare to the value measured before

-   Red teaming data anonymization [@Jansen2026_PuttingPrivacyTesta]

*Include exercise on calculating the privacy level with k-anonymity like before in 2_1_Planning Privacy*

# Measuring Utility

*Provide overview of utility measurements and maybe try out one*

-   utility indices [@Carvalho2023_SurveyPrivacyPreservingTechniques]
    -   predictive performance measures for machine learning *(potentially as call-out box)*
    -   information loss measures:
        -   distance/distribution comparisons
        -   a penalty of transformations through generalisation and suppression
        -   statistical differences
-   assessing utility for the current use case
    -   perform statistical analysis before and after anonymization
    -   see if results are comparable

*Include exercise for calculating one information loss measure*

# Striking the Right Balance

-   iterative process: rework anonymization after measuring both

-   *explain the norms for acceptable values of privacy and utility indicators*

-   People to contact at LMU (data stewards? open science team?)

#### Learning Objective

-   After completing this part of the tutorial, you will be able to make informed decisions when balancing the risks and utility of the anonymized data.

#### Exercises

-   apply measurement of k-anonymity

-   apply measurement of utility

#### Resources, Links, Examples

-   examples in UK: <https://ukdataservice.ac.uk/deposit-data/sharing-experiences/>

# References
