# Begin Project
project:
  type: website
  pre-render: wget -nc https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-custom.scss
  post-render: rm lmu-osc-custom.scss
bibliography: references.bib
# End Project


# Begin Website
website:
  title: "Data Anonymization Course"
  page-footer: 
    center: "Copyright, 2026 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/REPO-NAME-HERE
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU_OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU_OSC_logo.svg){width="175"}
  
  
  navbar:
    right: 
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/REPO-NAME-HERE
          - text: Report a Bug
            url:  https://github.com/lmu-osc/REPO-NAME-HERE/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "FOUNDATIONS"
        contents:
          - href: 1_FOUNDATION/1_1_Introduction_data_privacy.qmd
            text: "Introduction"
          - href: 1_FOUNDATION/1_2_GDPR.qmd
            text: "GDPR"
          - href: 1_FOUNDATION/1_3_Personal_Data.qmd
            text: "Personal Data"
          - href: 1_FOUNDATION/1_4_Mechanisms.qmd
            text: "Mechanisms"
          - href: 1_FOUNDATION/1_5_Privacy_Concepts.qmd
            text: "Privacy Concepts"
      - section: "ANONYMIZATION PROCESS"
        contents:
          - href: 2_ANONYMISATION_TECHNIQUES/2_1_Planning_Privacy.qmd
            text: "Planning Privacy"
          - href: 2_ANONYMISATION_TECHNIQUES/2_2_Overview_Methods.qmd
            text: "Overview of Techniques"
          - href: 2_ANONYMISATION_TECHNIQUES/2_3_Non_Perturbative.qmd
            text: "Non-Perturbative Techniques"
          - href: 2_ANONYMISATION_TECHNIQUES/2_4_Perturbative.qmd
            text: "Perturbative Techniques"
          - href: 2_ANONYMISATION_TECHNIQUES/2_5_Deassociative.qmd
            text: "De-Associative Techniques"
          - href: 2_ANONYMISATION_TECHNIQUES/2_6_Synthetic.qmd
            text: "Synthetic Data"
          - href: 2_ANONYMISATION_TECHNIQUES/2_7_Choosing_technique.qmd
            text: "Choosing the Right Technique"
      - section: "BALANCING DATA PROTECTION AND OPENNESS"
        contents:
          - href: 3_PRIVACY_OPENNESS/3_1_Balancing.qmd
            text: "Balancing Tensions"
          - href: 3_PRIVACY_OPENNESS/3_2_Documentation.qmd
            text: "Documentation"
      - section: "ANONYMIZATION WORKFLOW"
        contents: 
          - href: 4_WORKFLOW/4_1_Summary.qmd
            text: "Summary"  
# End Website


# Begin Format
format:
  html:
    theme: 
      - cosmo
      - lmu-osc-custom.scss
    css: 
      - https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px
    include-in-header:
      - file: matomo-analytics.html
# End Format

# Begin Editor
editor: source
# End Editor
