# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/data-anonymization
website:
  title: "Data Anonymization Course"
  page-footer:
    border: false
    center: © 2026 Luisa Jansen. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/data-anonymization

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/data-anonymization
          - text: Report a Bug
            href: https://github.com/lmu-osc/data-anonymization/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "FOUNDATIONS"
        contents:
          - href: foundations/introduction-data-privacy.qmd
            text: "Introduction"
          - href: foundations/gdpr.qmd
            text: "The GDPR"
          - href: foundations/personal-data.qmd
            text: "Personal Data"
          - href: foundations/mechanisms.qmd
            text: "Privacy Mechanisms in Research"
          - href: foundations/privacy-concepts.qmd
            text: "Privacy Concepts"
      - section: "ANONYMIZATION PROCESS"
        contents:
          - href: anonymisation-techniques/planning-privacy.qmd
            text: "Assessing Privacy Risks"
          - href: anonymisation-techniques/overview-methods.qmd
            text: "Overview of Techniques"
          - href: anonymisation-techniques/non-perturbative.qmd
            text: "Non-Perturbative Techniques"
          - href: anonymisation-techniques/perturbative.qmd
            text: "Perturbative Techniques"
          - href: anonymisation-techniques/deassociative.qmd
            text: "De-Associative Techniques"
          - href: anonymisation-techniques/synthetic.qmd
            text: "Synthetic Data"
          - href: anonymisation-techniques/choosing-technique.qmd
            text: "Choosing the Right Technique"
      - section: "BALANCING DATA PROTECTION AND OPENNESS"
        contents:
          - href: privacy-openness/balancing.qmd
            text: "Balancing Tensions"
          - href: privacy-openness/documentation.qmd
            text: "Documentation"
      - section: "ANONYMIZATION WORKFLOW"
        contents:
          - href: workflow/summary.qmd
            text: "Summary"
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
include-after-body:
  - file: footer/footer.html
# End Includes

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
# we recommend just extending the definition below if you need to make format changes
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
