---
title: "About"
date: 2026-07-09
citation:
  type: "webpage"
  title: "Data Anonymization Course"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/
  doi: "DOI HERE"
author:
  - name: Luisa Jansen
    roles: [conceptualization, software, resources, visualization, writing - original draft, writing - editing & review]
    degrees:
      - M.Sc.
    affiliation: 
      - id: UNIBE
        name: University of Bern
        ror: https://ror.org/02k7v4d05
        isni: 0000000107265157
    orcid: 0000-0001-8126-1306
google-scholar: true
---


# Contributors

This site was authored by Luisa Jansen, and edits/contributions were made by EDITORS/AUTHORS.

# Licenses

The overall project is available under the **[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)** license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the **[CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/)** license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

# Notes

This tutorial was primarily written in 2026 using R (R version 4.5.3 (2026-03-11 ucrt)). Major changes to R can be found at the [R's website](https://www.r-project.org/) for the most up-to-date information, and to confirm that our tutorial is not out-of-date. 

