---
title: "Welcome to the Data Anonymization Course"
---

This website is a work in progress. Please come back later in 2026 :)

# Tutorial Overview

This **self-paced tutorial** on anonymization of quantitative research data is intended to take three hours to complete.

The tutorial is split into the following sections:

1.  [**FOUNDATIONS OF DATA PROTECTION**](1_FOUNDATION/1_1_Introduction_data_privacy) talks about data protection basics in ethics and law, mechanisms of data protection in research, and foundational terms.
2.  [**DATA ANONYMIZATION PROCESS**](2_ANONYMISATION_TECHNIQUES/2_1_Planning_Privacy) walks you through the process of anonymizing your research data based on example data.
3.  [**BALANCING DATA PROTECTION AND OPENNESS**](3_PRIVACY_OPENNESS/3_1_Balancing) presents methods for aligning your data protection and open science interests.
4.  [**ANONYMIZATION WORKFLOW**](4_WORKFLOW/4_1_Summary) closes this tutorial by summarizing the learned workflow.

# What You'll Learn

By the end of this tutorial, you will be able to:

-   **Understand key concepts** in the world of privacy (e.g., anonymization, k-anonymity)

-   **Classify data** in relevant categories for data protection (e.g., personal data, sensitive data)

-   **Apply anonymization techniques** using R in a coherent workflow

-   **Make informed decisions when balancing the risks and utility** of the anonymized data

# What You Will **NOT** Learn

You will not learn anything other than anonymization of quantitative data.

Here are a few helpful links for other data types:

-   Anonymizing neuroimaging metadata ([recommendations](https://doi.org/10.1162/IMAG.a.1144))
-   Anonymizing qualitative textual data ([video tutorial for QualiAnon](https://www.youtube.com/watch?v=RYQn4DjdKmo))
-   Anonymizing sensitive qualitative data ([lecture](https://www.youtube.com/watch?v=-Pha3EINF3s&ab_channel=CenterforOpenScience) and [tutorial](https:/doi.org/10.1037/tra0001358))

# Prerequisites

-   You need basic R skills (e.g., loading data and packages).

-   Necessary software: R and RStudio
