---
title: "Key Concepts and Principles - planning anonymity in data collection"
---

# Definitions in the GDPR

Below are some definitions that the GDPR operates on. Click on the arrow to the right to expand.



::: {.callout-note collapse="true"}
# Personal data

 is any information connected to a person who can be identified, either directly (for example, by their name or ID number) or indirectly (for example, through location, online accounts, or details about their body, health, finances, culture, or social life).
:::

::: {.callout-note collapse="true"}
# Processing

 means doing anything with personal data, whether by hand or with a computer. This includes things like collecting, recording, organizing, storing, changing, looking up, using, sharing, combining, limiting, deleting, or destroying the data.

:::

::: {.callout-note collapse="true"}
# Controller

 Controller means the person, company, public authority, or organization that decides why personal data is processed and how it is processed. In some cases, the law itself decides who the controller is or sets rules for how the controller is chosen.

:::

::: {.callout-note collapse="true"}
# Processor

Processor means the person, company, or organization that processes personal data on behalf of the controller. They follow the controller’s instructions and don’t decide the purpose or the means of the processing themselves.

:::



-Data collection and consent mechanisms
-Data minimization and purpose limitation
-Privacy by design and default
